### ISSUE TITLE
can you share link to download this paper - related to DG-LNRT paper

### ISSUE THREAD

**Issue by Sandy4321** [czopluoglu/dg-lnrt#1]
can you share link to download this paper - related to DG-LNRT paper

**Comment by Sandy4321** [comment]
OK found this 
https://osf.io/preprints/psyarxiv/bqa3t/

is it needed link ?

by way
I see you are world wide known professional in Preknowledge research 

May you help fine link to download big data set related to  Preknowledge  detection?

**Comment by czopluoglu** [comment]
Here is the published paper associated with this repository.

[2022_Kasli, Zopluoglu, and Toton.pdf](https://github.com/czopluoglu/dg-lnrt/files/13430018/2022_Kasli.Zopluoglu.and.Toton.pdf)

**Comment by Sandy4321** [comment]
suuuuuper
thanks a lot
by the way do you know from where to download conventional big data set for detecting  Examinees with Item Preknowledge
tabular data:
each row is Examinee
each column is question with values : 0 - question was not shown to Examinee; 1 correct answer; -1 wrong answer

as professionals in this field , you know such a web link
thanks a lot in advance ....
